import Navbar from "./component/layout/Navbar";
import "./globals.css";

export const metadata = {
  title: "Art Portfolio: Sample",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
